/**
 * @file eventHandler.hpp
 * @author Aidan McIntosh
 * @brief Declares the EventHandler class, responsible for acquiring and
 *        normalising raw sensor inputs into a unified event stream.
 */

#pragma once

#include <cstdint>
#include <condition_variable>
#include <mutex>
#include <queue>

#include "drivers/i2c_bus.hpp"
#include "drivers/pressure_sensor.hpp"
#include "drivers/tof_sensor.hpp"
#include "drivers/cap_sensor.hpp"

/**
 * @brief Represents a generic input event produced by hardware sensors.
 *
 * This struct encapsulates all possible raw input types generated by the system.
 * Only the field relevant to the event type should be considered valid.
 */
struct RawInputEvent {
    /**
     * @brief Enumeration of supported input event types.
     */
    enum class Type {
        ToFDistance,        /**< Time-of-Flight distance measurement (mm). */
        PressureReading,    /**< Breath/pressure sensor reading. */
        MouthpieceReading,  /**< Capacitive embouchure input. */
        Keycontrol          /**< Keyboard/control input for testing or overrides. */
    };

    Type type{};                /**< Type of the event. */
    uint16_t tofDistance{};     /**< Distance measurement (valid if ToFDistance). */
    float pressureReading{};    /**< Pressure value (valid if PressureReading). */
    int8_t mouthpieceReading{}; /**< Embouchure state (valid if MouthpieceReading). */
    char keycontrol{};          /**< Key input (valid if Keycontrol). */
};

/**
 * @brief Handles acquisition and dispatch of raw sensor input events.
 *
 * This class interfaces with all hardware input devices (ToF sensor, pressure
 * sensor, capacitive touch sensor) and converts their outputs into a unified
 * event stream. Events are pushed into an internal queue and consumed by other
 * system components.
 *
 * A thread-safe producer-consumer model is used:
 * - Sensor callbacks or polling logic push events into a queue.
 * - Consumers block on waitForEvent() until data is available.
 *
 * The class also supports a test mode, where hardware interaction is bypassed,
 * allowing controlled input injection without physical devices.
 */
class EventHandler {
public:
    /** @brief Alias for the internal event queue type. */
    using EventQueue = std::queue<RawInputEvent>;

    /**
     * @brief Constructs the EventHandler.
     * @param isTest Enables test mode (disables hardware-dependent behaviour).
     */
    EventHandler(bool isTest);

    /**
     * @brief Initialises all input devices.
     * @return True if all devices were successfully initialised, false otherwise.
     *
     * Must be called before start().
     */
    bool initialise();

    /**
     * @brief Starts event acquisition.
     *
     * Begins polling or interrupt-driven handling of input devices and
     * populates the internal event queue.
     */
    void start();

    /**
     * @brief Blocks until an event is available and returns it.
     * @return The next RawInputEvent in the queue.
     *
     * Thread-safe. Intended for use by consumer threads.
     */
    RawInputEvent waitForEvent();

private:
    /**
     * @brief Pushes a new event into the queue.
     * @param event The event to enqueue.
     *
     * Notifies any waiting consumer threads.
     */
    void pushEvent(const RawInputEvent& event);

    /**
     * @brief Processes a ToF sensor reading.
     * @param distance Measured distance in mm.
     */
    void handleToFDistance(uint16_t distance);

    /**
     * @brief Processes a key control input.
     * @param key Input character.
     */
    void handleKeyControl(char key);

    /**
     * @brief Processes an embouchure (capacitive sensor) reading.
     * @param embouchure Discrete embouchure value.
     */
    void handleEmbouchure(int8_t embouchure);

    /**
     * @brief Processes a pressure sensor reading.
     * @param pressure Measured pressure value.
     */
    void handlePressureReading(float pressure);

    /** @brief Queue storing pending input events. */
    EventQueue eventQueue;

    /** @brief Mutex protecting access to the event queue. */
    std::mutex eventQueueMutex;

    /** @brief Condition variable used to signal arrival of new events. */
    std::condition_variable eventQueueCv;

    /** @brief I2C bus interface used by connected sensors. */
    I2CBus bus;

    /** @brief Time-of-Flight distance sensor. */
    ToFSensor tofSensor;

    /** @brief Pressure sensor for breath input. */
    PressureSensor pressureSensor;

    /** @brief Capacitive touch sensor for embouchure detection. */
    CAP1188 cap1188;

    /**
     * @brief Flag indicating test mode operation.
     *
     * When enabled, hardware interaction is bypassed and input handling
     * functions may operate on simulated data instead.
     */
    bool isTestMode = false;
};